# Generated by Django 2.2.6 on 2019-11-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_auto_20191113_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('CRM_table_list', '可以查看kingadmin每张表里所有的数据'), ('CRM_table_list_view', '可以访问kingadmin表里每条数据的修改页'), ('CRM_table_list_change', '可以对kingadmin表里的每条数据进行修改'), ('CRM_table_obj_add_view', '可以访问kingadmin每张表的数据增加页'), ('CRM_table_obj_add', '可以对kingadmin每张表进行数据添加'))},
        ),
    ]
