# Generated by Django 2.2.6 on 2019-11-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20191107_1119'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=None, related_name='stu_account', to='CRM.UserProfile')),
                ('profile', models.OneToOneField(on_delete=None, to='CRM.CustomerInfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
